// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWt6hIT5UfObdvgp1XaiqhyI1jS6a0ovU',
    appId: '1:363408732813:web:242dfaf8dd5f24d0b1a8c4',
    messagingSenderId: '363408732813',
    projectId: 'meny-admin-staging',
    authDomain: 'meny-admin-staging.firebaseapp.com',
    storageBucket: 'meny-admin-staging.appspot.com',
    measurementId: 'G-VL6005PE5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2wMjFlCrJ87zKrAAwMJq6BNLc66Jm-hM',
    appId: '1:363408732813:android:89f7be1123d5d90cb1a8c4',
    messagingSenderId: '363408732813',
    projectId: 'meny-admin-staging',
    storageBucket: 'meny-admin-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb7I2hTC6fuh_JjIvQubSKK5pU0bd31_8',
    appId: '1:363408732813:ios:d6446e8812d0097ab1a8c4',
    messagingSenderId: '363408732813',
    projectId: 'meny-admin-staging',
    storageBucket: 'meny-admin-staging.appspot.com',
    iosClientId:
        '363408732813-mgme4npvg2eo5gtr9tp0960vlvf9grr0.apps.googleusercontent.com',
    iosBundleId: 'io.doppelsoft.menyAdmin.stg',
  );
}
