// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7D1tbCq8nOxNErhggkGU2_z5yDISi9sA',
    appId: '1:601796248290:web:a5e9e34b933974fa3b14bb',
    messagingSenderId: '601796248290',
    projectId: 'meny-admin-development',
    authDomain: 'meny-admin-development.firebaseapp.com',
    storageBucket: 'meny-admin-development.appspot.com',
    measurementId: 'G-86LCHT5ZP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5v5EWNyV-F9_Abfsm6lZ2sdMYU7njM7o',
    appId: '1:601796248290:android:2b8361e58cacf9693b14bb',
    messagingSenderId: '601796248290',
    projectId: 'meny-admin-development',
    storageBucket: 'meny-admin-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_VzFxQLi-hUaKY_QugOtUP9sAjEyc86Q',
    appId: '1:601796248290:ios:59a093d6cea5b7f93b14bb',
    messagingSenderId: '601796248290',
    projectId: 'meny-admin-development',
    storageBucket: 'meny-admin-development.appspot.com',
    iosClientId: '601796248290-5g3n3qk4krru5rf1fckfbkqfu73ghubg.apps.googleusercontent.com',
    iosBundleId: 'io.doppelsoft.menyAdmin.dev',
  );
}
