// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:meny_core/meny_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQbfZXPd5OtGQAXKY6FUQunr1Sxdpq8Hg',
    appId: '1:907023061822:web:84bf19e6a4c97769bb526f',
    messagingSenderId: '907023061822',
    projectId: 'meny-admin-production',
    authDomain: 'meny-admin-production.firebaseapp.com',
    storageBucket: 'meny-admin-production.appspot.com',
    measurementId: 'G-ZYVF5S5WNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQETcehJJgg__wTrCMTbG_4vua3kOPsI',
    appId: '1:907023061822:android:9432741816ef0072bb526f',
    messagingSenderId: '907023061822',
    projectId: 'meny-admin-production',
    storageBucket: 'meny-admin-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJRmsZnS6FqpeZxC5R140NnmuefRKCTVw',
    appId: '1:907023061822:ios:edd2e5069473b7d0bb526f',
    messagingSenderId: '907023061822',
    projectId: 'meny-admin-production',
    storageBucket: 'meny-admin-production.appspot.com',
    iosClientId:
        '907023061822-4rj9ssra7ces84s81v227kvs757rg757.apps.googleusercontent.com',
    iosBundleId: 'io.doppelsoft.menyAdmin',
  );
}
